### ISSUE TITLE
Infinitton device not recognized

### ISSUE THREAD

**Issue by jermg77** [bitfocus/companion-satellite#34]
Infinitton keypads are not recognized, whereas they do work properly in the local version of Companion.

Thanks!

-Jeremy

**Comment by Julusian** [comment]
Infinitton devices arent supported currently, as I do not have one to test with so couldnt be sure I was doing something that would work..
If you are willing to test it I can give it a try

**Comment by jermg77** [comment]
I’d be happy to test it. Thanks!

**Comment by Julusian** [comment]
I have pushed some changes to allow this.
The minimum companion version required has changed to 2.2.0.

I suspect I have gotten the key order wrong, could you confirm that is the case? Other than that I think everything should be fine

**Comment by Julusian** [comment]
@jermg77 have you been able to test this?

**Comment by jermg77** [comment]
Hi Julian,

I’m terribly sorry, I’ve been so slammed with traveling work that this got put on the back burner… I will try to have a look at it this week.

Thanks!

-Jeremy

**Comment by Tdocwhowar** [comment]
just started testing satellite and it worked for one day then stopped companion will not see device, have restarted both software and still wont connect, I updated companion to 2.2.1 and still wont see it, am I missing something?

**Comment by Julusian** [comment]
@Tdocwhowar is that satellite worked for one day, or the infinitton with satellite? are you able to test if streamdecks are working?
is anything shown on the infinitton, or is it the default (black or infinitton logo? I have no idea what they do) when it is should be working?

**Comment by Julusian** [comment]
I believe this is now working. It is probably a bit buggy on arm based macos, but that is a different issue that is being looked at elsewhere
